"""Fix order_items id autoincrement

Revision ID: 07f0f7fb91bb
Revises: 5803601a55c7
Create Date: 2025-10-23 00:28:59.719939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07f0f7fb91bb'
down_revision: Union[str, Sequence[str], None] = '5803601a55c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'menu_item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'menu_item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
