"""Add category to menu_items

Revision ID: 5803601a55c7
Revises: 
Create Date: 2025-10-23 00:16:54.005602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5803601a55c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.alter_column('companies', 'api_key',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('order_items', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'item_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_ids', mysql.JSON(), nullable=False))
    op.drop_column('orders', 'created_at')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_column('order_items', 'quantity')
    op.drop_column('order_items', 'id')
    op.alter_column('companies', 'api_key',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('whatsapp_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('order_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('customers_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    # ### end Alembic commands ###
